export const getAllDocumentFlashCards = [
  {
    id: 16,
    type: 'Generated',
    topic: null,
    question: 'Zentrale Gefühle im Gedicht',
    answerStatus: null,
    correctAnswer:
      'Müdigkeit, Schmerz, Wunsch nach Frieden und Erlösung von weltlichem Leid.',
    transliterationId: null,
    isFavorite: false,
    answer: null,
    restricted: false,
    __typename: 'FlashCard',
  },
  {
    id: 15,
    type: 'Generated',
    topic: null,
    question: "Wanderer's Nightsong I (Übersetzung)",
    answerStatus: null,
    correctAnswer:
      'Die englische Übersetzung des Gedichts, die die gleiche Bitte um Frieden und Erlösung von Schmerz ausdrückt.',
    transliterationId: null,
    isFavorite: false,
    answer: null,
    restricted: false,
    __typename: 'FlashCard',
  },
  {
    id: 14,
    type: 'Generated',
    topic: null,
    question: 'Stilmittel im Gedicht',
    answerStatus: null,
    correctAnswer:
      "Das Gedicht verwendet Anrufung (Apostrophe) und Wiederholung, z.B. 'Der du von dem Himmel bist', um die Bitte um Frieden zu verstärken.",
    transliterationId: null,
    isFavorite: false,
    answer: null,
    restricted: false,
    __typename: 'FlashCard',
  },
  {
    id: 13,
    type: 'Generated',
    topic: null,
    question: 'Thema des Gedichts',
    answerStatus: null,
    correctAnswer:
      'Das Gedicht thematisiert die Sehnsucht nach Frieden und Erleichterung von Schmerz und Leid durch eine himmlische Kraft.',
    transliterationId: null,
    isFavorite: false,
    answer: null,
    restricted: false,
    __typename: 'FlashCard',
  },
  {
    id: 12,
    type: 'Generated',
    topic: null,
    question: 'Der du von dem Himmel bist (Gedicht)',
    answerStatus: null,
    correctAnswer:
      'Ein Gedicht, das den Himmel anruft, um Leid und Schmerzen zu stillen und Frieden in das Herz zu bringen.',
    transliterationId: null,
    isFavorite: false,
    answer: null,
    restricted: false,
    __typename: 'FlashCard',
  },
];
